### ISSUE TITLE
problemi con BLOC MAIUSC

### ISSUE THREAD

**Issue by knickita** [integr-abile/audiofunctions2.0#16]
se si scrivono delle variabili in stampatello, il validatore di funzioni non le riconosce.. vogliamo convertire tutto lowercase, così da evitare problemi?
latex prevede alcuni comandi scritti in maiuscolo o non ci sono distinzioni tra uppercase e lowercase?

**Comment by Mattia541993** [comment]
secondo me tutto quello che ci serve nel nostro contesto è [qui](https://it.wikipedia.org/wiki/Aiuto:Formule_matematiche_TeX) e non dovrebbero servirci lettere maiuscole, quindi se dai un'occhiata anche tu e mi confermi questa cosa per me possiamo prevedere tutto _lowercase_

**Comment by knickita** [comment]
confermo che possiamo fare tutto lowercase.
lo implemento!
