### ISSUE TITLE
evitare di fare import dei plugin

### ISSUE THREAD

**Issue by knickita** [integr-abile/audiofunctions2.0#7]
i file javascript che sono dentro la cartella plugin, possono essere auto importati (per evitare di chiamare import ogni volta).
guardare qui per capire come farlo:
[https://nuxtjs.org/docs/directory-structure/plugins/#es6-plugins](https://nuxtjs.org/docs/directory-structure/plugins/#es6-plugins)

**Comment by Mattia541993** [comment]
Al posto di importare tramite `import .... from ...` ora guarda nelle varie cartella dei plugin il metodo `inject("nome",<oggetto o funzione>)`. In un componente nella parte JS chiama quell'oggetto tramite `this.$<nome>` e se è una funzione puoi scrivere `this.$funzione(param)`. Ad esempio in `validate-function.mjs` ho fatto `inject("validateFunction", (fnString) => ConvertFunction(fnString));` e dal componente lo chiami come `this.$validateFunction(valore)`
